### ISSUE TITLE
[Compile Error] 'sha256_word': undeclared identifier

### ISSUE THREAD

**Issue by sharkbait2** [mcfriend99/Bird#25]
## Description
I'm trying to compile bird, with on windows with MSVC 19.26 (cmake 3.20) but the build failed with an error `error C2065: 'sha256_word': undeclared identifier`

Here is the line that makes the error.
https://github.com/mcfriend99/Bird/blob/main/src/win32.c#L90

## What I've done so far

Run the command and compiled with MSVS 2019
```
mkdir build && cd build
cmake ..
```

And I cannot find the symbol `sha256_word` defined anywhere?

**Comment by mcfriend99** [comment]
Fixed by PR #26
